[package]
name = "lat-gpu-cuda"
version = "0.1.0"
edition = "2021"

[dependencies]
cudarc = { version = "0.11", default-features = false, features = ["cuda-12040"] }
lat-core = { path = "../lat-core" }