[package]
name = "lat-gpu-cuda"
version = "0.1.0"
edition = "2021"

[dependencies]
cudarc = { version = "0.19", features = ["cuda-version-from-build-system", "driver", "nvrtc"] }
lat-core = { path = "../lat-core" }
